#pragma once

#define SPLIT_ACTIVITY_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_OLED_ENABLE
#define SPLIT_WPM_ENABLE

#define OLED_TIMEOUT 0  // managed at runtime via oled_timeout_mins
#define SPLIT_TRANSACTION_IDS_KB SYNC_OLED_TIMEOUT

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_SLEEP
#    define RGB_MATRIX_LED_FLUSH_LIMIT 16
#    define RGB_MATRIX_HUE_STEP 5
#    define RGB_MATRIX_SAT_STEP 5
#    define RGB_MATRIX_VAL_STEP 5
#    define RGB_MATRIX_SPD_STEP 10

#    define ENABLE_RGB_MATRIX_ALPHAS_MODS
#    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#endif
